const productList = [
  {
    id: "0",
    name: "RTX 3090",
    description: "Placa de Vídeo",
    price: 1599.99,
    quantity: 15,
    img: "teste",
  },
  {
    id: "1",
    name: "Ryzen 9 5900X",
    description: "Processador",
    price: 599.99,
    quantity: 25,
    img: "teste",
  },
  {
    id: "2",
    name: "Samsung 4K TV",
    description: "Smart TV",
    price: 999.99,
    quantity: 8,
    img: "teste",
  },
  {
    id: "3",
    name: "iPhone 13 Pro",
    description: "Smartphone",
    price: 1099.99,
    quantity: 12,
    img: "teste",
  },
  {
    id: "4",
    name: "Sony",
    description: "Fones de Ouvido",
    price: 249.99,
    quantity: 18,
    img: "teste",
  },
  {
    id: "5",
    name: "Samsung",
    description: "Tablet",
    price: 599.99,
    quantity: 10,
    img: "teste",
  },
  {
    id: "6",
    name: "Dell XPS 13",
    description: "Notebook",
    price: 1299.99,
    quantity: 14,
    img: "teste",
  },
  {
    id: "7",
    name: "Logitech",
    description: "Teclado Mecânico",
    price: 129.99,
    quantity: 30,
    img: "teste",
  },
  {
    id: "8",
    name: "Logitech G",
    description: "Mouse Gamer",
    price: 99.99,
    quantity: 27,
    img: "teste",
  },
  {
    id: "9",
    name: "LG 4K Monitor",
    description: "Monitor",
    price: 349.99,
    quantity: 11,
    img: "teste",
  },
];

export default productList;
